### ISSUE TITLE
"Configure CNApy" and "Configure cobrapy" fields missing from Config menu

### ISSUE THREAD

**Issue by lauradunphy** [cnapy-org/CNApy#434]
Thanks for sharing such a great tool with the community! 

From your documentation, it appears that there should be options in the Config menu called "Configure CNApy" and "Configure cobrapy" where users can set their own solvers, etc. When CNApy is installed as a conda package on an a mac with python version 3.10.4, these menu options appear to be absent. This is the config menu in the installed version: 

<img width="279" alt="config_menu" src="https://user-images.githubusercontent.com/38433568/199089847-de75a4fc-e5b5-4547-b595-a6fdc7dcd326.png">

Have you seen this issue before? Ideally, I'd like to be able to change the solver to enable working with larger models without erroring out.

<img width="415" alt="config_error" src="https://user-images.githubusercontent.com/38433568/199089969-ec51a6c3-c95a-4b80-ab87-b8760a492c85.png">

Apologies if you've addressed this issue in another post. 

Many thanks,

Laura

**Comment by axelvonkamp** [comment]
Hi,

thanks for the bug report. I have noticed these missing menu entries on another Mac before, so it must be related to this platform. It is very weird because I have no idea why these entries are missing whereas the rest of the menus appears OK. Unfortunately we don't have access to any Macs at the moment and cannot investigate ourselves what is going on.
As a workaround you can set the solver via the CNApy console like this:
```
cna.appdata.project.cobra_py_model.solver = 'cplex'
```
or
```
cna.appdata.project.cobra_py_model.solver = 'gurobi'
```
You can also set 'glpk' but I am not sure if this runs on a Mac. The error message you posted indicates that your model is too large to be handled by the trial version of Gurobi, so you would need to install the full version if you want to use this solver.

**Comment by lauradunphy** [comment]
Hi,

Thanks for the quick response! Helpful to know it was a Mac issue. Your recommended commands didn't appear to change the solver, but getting the full version of Gurobi fixed the issue!  

In case it is helpful, I think (?) glpk does work on Mac. At least, some version of glpk is the default solver used by cobrapy. 

Many thanks,
Laura
