### ISSUE TITLE
I installed the windows version by cnapy-installer.exe but the CNApy icon wasn't created 

### ISSUE THREAD

**Issue by BatistaB** [cnapy-org/CNApy#463]
Hello,

someone could help me? I can't use the app on windows cause the CNApy icon wasn't created after installation process.
(I'm not from computer science and my coding skills are bad, sorry if this issue was ridiculous)

Help the newbie :)
thanks

**Comment by Paulocracy** [comment]
Hello! That's not a ridiculous issue, actually, creating a bug-free Windows .exe installer is one of our main problems xD and every message about problems with it helps us :-) Regarding your issue, I just tried the installer on my computer and it worked fine :3, so that answering the following questions would greatly help us in investigating the problem:

1. Did you see the message that CNApy was successfully installed at the end of the installation process?
2. Did you give the installer elevated (administrator-like) rights at the beginning? In other works, did you click on "Yes" when WIndows asked if you are ok with "severe" hard drive writing rights?
3. Can you search, in the folder where you installed CNApy (usually a subfolder called "CNApy" at your selected location), for a "cnapy.exe"? If it exists, you should be able to start CNApy by double-clicking on it.

**Comment by BatistaB** [comment]
Hello, thank for replying !

So, lets me see:
1) Yes, I saw the message 'CNApy was successfully installed" and the follow steps.
2) I tried it too.. But unfortunately the same issue occur. 
3) So, it's the key point for my issue. The CNAPy.exe wasn't created. When I look inside of the CNApy folder I see only:
- cnapy-uninstaller.exe
- miniconda folder

I have been trying to install in different folders on my pc but every time the same issue occurs. The .exe doens't exist. 
check my gif for the installation process.

![try1](https://user-images.githubusercontent.com/91222473/221702286-c25c6b70-2f8d-415d-901a-a53e36b07668.gif)

thank you for your attention

**Comment by Paulocracy** [comment]
Hello again and thank you for your extensive and helpful answer! Regarding point number 3, could you check whether maybe a "cnapy.exe" or at least a "cnapy" subfolder is inside of the "miniconda" folder (just by searching it with the file explorer)? Then I could deduce whether or not the conda package itself may have a problem :3

**Comment by BatistaB** [comment]
Hello 

I tried to find CNAPY.exe in miniconda folder (and subfolders) but didn't work. The cnapy.exe doesn't exist in any folder.

Here the print of miniconda folder.
![image](https://user-images.githubusercontent.com/91222473/221809226-c4d45a93-a1b3-468f-937a-fa340272a9d6.png)

**Comment by Paulocracy** [comment]
Hello again! Your answer helps me a lot at it looks like, strangely, Miniconda wasn't installed correctly on your device (there are some missing folders and files such as the important "condabin" subfolder). To investigate this problem, and if you have time, I would ask you to install Miniconda and cnapy "by hand". You can do it as follows:
1. Download the latest Miniconda from https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
2. Run it and follow the installation instructions while remembering where you installed it. If you've already installed Python on your system and you want to avoid confusion with it, just deactivate all settings which state that Miniconda would added to the system's PATH.

Additionally, to install cnapy easily, I created a small .bat (Windows console) script which tries to install the cnapy conda package directly using your new Miniconda installation. It is added as an attachment to this message in a zipped form. To run it, do the follwing:

1. Download the zip [zInstallCnapy.zip by clicking here](https://github.com/cnapy-org/CNApy/files/10849317/zInstallCnapy.zip)
1. Unzip the zip file
2. Copy the resulting unzipped "zInstallCnapy.bat" file into the "condabin" subfolder of your new Miniconda installation
3. Double-click on "zInstallCnapy.bat"
4. Hopefully, you don't see any error messages (if this happens, please post them here) and CNApy should be successfully installed

**Comment by BatistaB** [comment]
Hello Paulo,

I did all steps and happily everything worked!
Now I can invest my time learning how to use it in metabolic engineering/FBA etcs.

I saw that your team developed the StrainDesign package and I think the next step is to learn how I can integrate these two.

I'm so grateful with your help. 
Thanks a lot.

best regards

![worked](https://user-images.githubusercontent.com/91222473/222001160-ac6ed5f1-4178-4bd8-9848-082c83e6e08f.png)

**Comment by Paulocracy** [comment]
Hello!
I'm glad that the installation protocol worked successfully. Maybe we'll abolish the current installer and just provide this alternative assisted installation route :3
Regarding StrainDesign, its GUI can be found in the "Analysis" menu entry under "Computational Strain Design"->"Compute Strain Designs...". StrainDesign's documentation is available [here](https://straindesign.readthedocs.io/en/latest/), although it is currently written only in its Python package form. However, you can translate and save nearly all examples using the assistance of the StrainDesign GUI in CNApy.
Since your installation worked well, I'll close this issue but if you have any further issues or questions you are of course free to do any of writing an issue, using our Gitter chat room or using the CNApy GitHub discussions :-) And have fun in the world of constraint-based metabolic engineering :D
